#!/bin/bash


kubectl apply -f ./prometheus.yaml
kubectl apply -f ./grafana.yaml
kubectl apply -f ./kiali.yaml

kubectl -n istio-system delete svc kiali
kubectl -n istio-system expose pod $(kubectl -n istio-system get pod -l app.kubernetes.io/name=kiali -o jsonpath='{.items[*].metadata.name}') --type=NodePort --name=kialiport --target-port=20001 --port=20001

